version: '3.7'

services: 
    bot:
        image: mrllama12/test-discord-bot:latest
        environment:
            ENV: prod
        secrets:
            - token_discord_bot
secrets:
    token_discord_bot:
        external: true