name: docker build and publish
on:
#   push:
#     branches: [ master ]
  release:
  push:
    types: published
    tags: v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get tag
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
    - name: Build and publish image
      uses: zmingxie/docker_buildx@master
      with:
        publish: true
        imageName: mrllama12/test-discord-bot
        tag: latest,${{ env.RELEASE_VERSION }}
        platform: linux/amd64,linux/arm/v7
        dockerHubUser: ${{ secrets. DOCKER_USERNAME }}
        dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
