on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get tag
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.3.0
      with:
        platforms: linux/amd64,linux/arm/v7  
    - name: docker login
      uses: azure/docker-login@v1
      with:
        login-server: registry.hub.docker.com
        username: ${{ secrets. DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
